### ISSUE TITLE
Вычисление температуры аналогично приложению, с фильтрацией аномальных значений

### ISSUE THREAD

**Issue by radio-van** [dentra/esphome-tion#10]
"Родное" приложение Tion выводит температуру не напрямую с датчиков, а считает по показаниям с двух датчиков:
```
int(((unknown <= 0 ? current : unknown) + (current <= 0 ? unknown : current)) / 2)
```
Имеет смысл использовать аналогичный расчет и в ESPHome с дополнительной отбраковкой слишкрм высоких значений (>30 градусов), т.к. бывает, что один из датчиков может начинать "забрасывать" значения вплоть до 70 градусов.

**Comment by dentra** [comment]
в мастере
https://github.com/dentra/esphome-tion/blob/31243277ec8afb9f4b52b43d7415de4ebce7ddfe/components/tion-api/tion-api-3s.h#L80
