### ISSUE TITLE
Просто наблюдение - в обновлённом приложении Тиона есть обновление прошивки

### ISSUE THREAD

**Issue by u17194907425** [dentra/esphome-tion#11]
Сабж.

Попытался поискать список изменений, но не нашёл. Написал им на почту в службу поддержки.
Интересно, кто-нибудь обновлялся и всё-ли после обновления работает.

**Comment by AleksandrKozin** [comment]
Что-нибудь ответили?

**Comment by dentra** [comment]
Я не имею никакого отношения к Tion. 
Весь проект построен на реверс инжиниринге протокола обмена собственных устройств и устройств сообщества.

**Comment by didjeru** [comment]
Возможно это для прошивки Magic Air?

**Comment by u17194907425** [comment]
> Я не имею никакого отношения к Tion.
> Весь проект построен на реверс инжиниринге

Это и не подразумевалось. Мысль была в том, чтобы проинформировать сообщество и поделиться, если есть чем. Вдруг, кто уже обновился и может подтвердить, что на работу с [esphome-tion](https://github.com/dentra/esphome-tion) это обновление не влияет.

> Что-нибудь ответили?
Пока ничего. Сегодня с утра (то есть через сутки) пришёл автоматический ответ, что моему обращению присвоен номер.

> Возможно это для прошивки Magic Air?
Возможно, но нет.

**Comment by u17194907425** [comment]
В теории, никакой регрессии от обновления быть не должно. Я исхожу из того, что уважаемый @dentra зареверсил интерфейс пульта и Magic Air (если мы говорим про блюпуп). Если они его изменят, то пульты просто перестанут работать.

И в то же время, интересно, что же они там поменяли.

**Comment by dentra** [comment]
В теории все должно продолжить работать иначе отвалятся родные пульты, которые работают по тому же самому протоколу.

**Comment by dentra** [comment]
думаю уже не актуально
