### ISSUE TITLE
Суммарное дневное потребление растёт при выключенном бризере

### ISSUE THREAD

**Issue by dentra** [dentra/esphome-tion#24]
> а так и задумано что суммарное дневное потребление растёт при выключенном бризере? глянул по диагонали код, там вроде нет поверки на то, включен бризер или нет, то есть похоже продолжает считать по установленной скорости

**Comment by dentra** [comment]
Необходимо добавить проверку на режим off в пакет tion_energy.yaml

**Comment by dentra** [comment]
В мастере. Можно использовать

**Comment by Dexter-Lucky** [comment]
Эта проблема на текущий момент имеет место быть как на 4s_ble, так и на lite.

**Comment by Dexter-Lucky** [comment]
Залил код из ветки next.
Проблема сохранилась. При этом как-то не корректно отображается мощность вентилятора как на 4s, так и на Lite. Режим ожидания показывает корректно, как в описании, 0,73 Вт, а вот при работе, мощность отображается в 10 раз больше.
Ниже скриншоты в выключенном состоянии (0,73 Вт)
![image](https://github.com/user-attachments/assets/86ccae32-5800-4615-ac0f-999cdbc4966c)
на третьей скорости (162 Вт)
![image](https://github.com/user-attachments/assets/6b27b1e0-59a6-4223-ae07-3c6032632c1e)

На выходных  постараюсь измерить реальное потребление бризера Lite и 4s . Результаты пришлю сюда.

**Comment by dentra** [comment]
10 кратное потребление поправил. буду благодарен за замеры

**Comment by Dexter-Lucky** [comment]
Сделал на выходных замеры, результаты во вложении.
Сразу оговорюсь, что измерял прибором с точностью до  1 Вт.
По бризеру 4s результаты очень сильно похожи на уже вшитые данные, за исключением потребления на 6 скорости. Там потребление  получилось 35 Вт.
По Lite значения ожидаемо получились сильно ниже, чем у 4s. Сначала даже не поверил,дважды перепроверял  все режимы.
[Бризеры мощность.xlsx](https://github.com/user-attachments/files/16590267/default.xlsx)

**Comment by dentra** [comment]
по 4S я константы усреднил

**Comment by dentra** [comment]
В коммите [6493316](https://github.com/dentra/esphome-tion/commit/64933161337937e1b733b9d63f6fefc1b6225d17) добавил возможность переопределить встроенные значения. Ниже пример как это можно сделать, значение потребляемой мощности необходимо умножить на 100, например переопределяем 6 скорость на 35 Вт:
```yaml
esphome:
  platformio_options:
    build_flags:
      - -DTION_4S_MAX_FAN_POWER6=3500
```

**Comment by dentra** [comment]
Решено
