### ISSUE TITLE
Нагрев даже в режиме fan_only

### ISSUE THREAD

**Issue by WeslyG** [dentra/esphome-tion#25]
После какого то из обновлений, заметил большое потребление тиона в энергомониторинге.
Полез разбираться, выяснил, что теперь даже в режиме "проветривание" если температура ниже нуля, то автоматом включается подогрев до нуля. Есть ли вариант отключить это поведение? Да я хочу холодный воздух в квартиру без обогрева, если он мне понадобиться, я переведу его в нагрев сам. 
Tion 4s ble версия плагина 2024.1.3

![image](https://github.com/dentra/esphome-tion/assets/12625945/e0131684-fef9-4874-9583-22a63692e050)
![image](https://github.com/dentra/esphome-tion/assets/12625945/085dc7a1-5133-4d20-8fa4-5a5a957e3fa8)

**Comment by dentra** [comment]
если температура входящего воздуха ниже 0, то обогрев включается автоматически самим тионом и это поведение изменить невозможно. это встроенная защита от обмерзания.

**Comment by WeslyG** [comment]
Воу, не знал этого, вроде раньше оно иначе работало, или просто статистику другую рисовало... Ну раз так, то ладно, спасибо за обьяснение
