### ISSUE TITLE
Error compiling ESP32 -  [build_flags] is an invalid option for [framework]

### ISSUE THREAD

**Issue by remezen** [dentra/esphome-tion#31]
![Снимок экрана 2024-05-30 205553](https://github.com/dentra/esphome-tion/assets/2427989/42200864-efb3-43f6-83f7-6f1e09b81218)

tion-4s-uart.yaml

Only line changed - - **packages/esp32.yaml**

**Comment by dentra** [comment]
already fixed in “next”

**Comment by dentra** [comment]
Исправлено в релизе 2024.8.0
