### ISSUE TITLE
Пропала температура наружного воздуха

### ISSUE THREAD

**Issue by Dexter-Lucky** [dentra/esphome-tion#35]
Почему то пропала температура наружного воздуха. Даже в атрибутах устройства ее нет.
Это и на 4s_ble и на lite воспроизводится.
Код прикрепляю.
Так же на 4s пропала информация о сроке замены фильтра, она почему то отображается теперь в оставшемся времени турбо режима.
ESP Home 2024.5.5

**Comment by dentra** [comment]
воспроизводиться ли эта проблема на бете (ветка next)? home assistant или spurt?

**Comment by Dexter-Lucky** [comment]
К сожалению не знаю, как использовать бета версию.
На текущий момент не обновляю ESP Home, т.к. не могу обновить платы на новой версии.
Home  Assistant

**Comment by dentra** [comment]
Вы хотели что-то прикрепить, но забыли. Покажите хоть скриншот

**Comment by Dexter-Lucky** [comment]
Прикладываю скриншоты
![image](https://github.com/dentra/esphome-tion/assets/127134937/aba3e2bd-8733-40f8-b1ca-13d86f043fe4)
![image](https://github.com/dentra/esphome-tion/assets/127134937/08b9229c-4a0c-4947-bc00-2d5a727af50d)
![image](https://github.com/dentra/esphome-tion/assets/127134937/050bb7de-9f4c-4f4f-ae5f-63423408ad3f)

**Comment by dentra** [comment]
Я очень надеюсь, что переименование вы делаете именно в HA, а не конфигурации прошивки т.к. из имени генерируется уникальный идентификатор, который попадает в HA, а с русскими буквами все плохо к сожалению.

покажите еще пожалуйста ваш конфиг.

**Comment by Dexter-Lucky** [comment]
Добрый день.
Тему можно закрывать.  При заливке оригинального конфига все показатели появились, и снова вернулась проблема с 4s ble (но это в отдельной теме).
Спасибо.
