### ISSUE TITLE
Проблема после обновления ESPHome до версии 2024.12.0

### ISSUE THREAD

**Issue by AlexNikitos** [dentra/esphome-tion#47]
После обновления интеграции ESPHome до версии 2024.12.0 мой Lilygo T-Dongle S3 тоже хочет обновиться, но теперь он даже вариацию не проходит и не обновляется. Получаю вот эту ошибку (сам yaml приложил):

```
INFO ESPHome 2024.12.0
INFO Reading configuration /config/esphome/tion-4s.yaml...
Failed config

esp32: [source /data/packages/f334921b/packages/esp32_uart.yaml:8]
  board: esp32-s3-devkitc-1
  
  ESP-IDF 4.4.7 may be supported by platformio/espressif32; please specify 'platform_version'.
  framework: 
    type: esp-idf
    version: 4.4.7
```

[tion-4s.yaml.txt](https://github.com/user-attachments/files/18186006/tion-4s.yaml.txt)

**Comment by u17194907425** [comment]
У себя решил добавлением вот этих строчек в конфиг. Всё как написано в сообщении об ошибке:

```
esp32:
  framework: 
    platform_version: platformio/espressif32
```
