### ISSUE TITLE
Положение заслонки как аргумент в персетах

### ISSUE THREAD

**Issue by radio-van** [dentra/esphome-tion#9]
На данный момент в пресетах можно указать желаемую температуру, режим (обогрев вкл/выкл) и скорость. Была бы полезной возможность указывать также положение заслонки (забор с улицы/забор из помещения) для создания пресета "очистки" помещения, когда бризер пропускает через свой фильтр внутрикомнатный воздух, выполняя функцию воздухоочистителя.

**Comment by dentra** [comment]
в мастере

**Comment by dentra** [comment]
в релизе
